version: "3.9"

services:
  db-replica:
    image: postgres:16
    container_name: db-replica
#    environment:
#      POSTGRES_USER: replicator
#      POSTGRES_PASSWORD: replicator123
    ports:
      - "5440:5432"
    volumes:
      - db-replica:/var/lib/postgresql/data
#      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
#      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
#    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    networks:
      - flask_async_network
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U replicator" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

networks:
  flask_async_network:
    external: true

volumes:
  db-replica:
    name: db-replica